DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS remedy;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE remedy (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL,
  potency_id integer NOT NULL,
  materia_medica_link TEXT NOT NULL DEFAULT '',
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE remedy_potency (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  potency TEXT NOT NULL
);

